# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 00:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=9)),
                ('ensemble', models.CharField(max_length=9)),
                ('netid', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('hometown', models.CharField(max_length=300)),
                ('movein_date', models.DateField()),
                ('medical_conditions', models.TextField()),
                ('dietary_needs', models.CharField(max_length=20)),
                ('years_tenure', models.CharField(max_length=3)),
                ('senior_ceremonies', models.BooleanField()),
                ('gender', models.CharField(max_length=6)),
                ('shoe_size', models.CharField(max_length=2)),
                ('tshirt_size', models.CharField(max_length=6)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_address', models.CharField(max_length=300)),
                ('parent_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
